"""cria tabela medicamentos

Revision ID: f3f0f908dae1
Revises: 
Create Date: 2026-06-25 14:24:37.769973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f0f908dae1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('substancia', sa.String(length=500), nullable=False),
    sa.Column('produto', sa.String(length=500), nullable=False),
    sa.Column('apresentacao', sa.String(length=500), nullable=False),
    sa.Column('laboratorio', sa.String(length=300), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('codigo_ggrem', sa.String(length=50), nullable=False),
    sa.Column('registro', sa.String(length=50), nullable=True),
    sa.Column('ean1', sa.String(length=20), nullable=True),
    sa.Column('classe_terapeutica', sa.String(length=200), nullable=True),
    sa.Column('tipo_produto', sa.String(length=100), nullable=True),
    sa.Column('regime_preco', sa.String(length=50), nullable=True),
    sa.Column('tarja', sa.String(length=100), nullable=True),
    sa.Column('pf_sem_impostos', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pf_0', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pmc_sem_impostos', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pmc_0', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pmc_12', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pmc_17', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pmc_18', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pmc_19', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pmc_20', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('restricao_hospitalar', sa.Boolean(), nullable=True),
    sa.Column('cap', sa.Boolean(), nullable=True),
    sa.Column('confaz_87', sa.Boolean(), nullable=True),
    sa.Column('icms_0', sa.Boolean(), nullable=True),
    sa.Column('comercializacao_2025', sa.String(length=10), nullable=True),
    sa.Column('data_coleta', sa.DateTime(), nullable=False),
    sa.Column('fonte_url', sa.Text(), nullable=True),
    sa.Column('data_publicacao_cmed', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicamentos_codigo_ggrem'), 'medicamentos', ['codigo_ggrem'], unique=True)
    op.create_index(op.f('ix_medicamentos_produto'), 'medicamentos', ['produto'], unique=False)
    op.create_index(op.f('ix_medicamentos_substancia'), 'medicamentos', ['substancia'], unique=False)
    op.create_index('ix_medicamentos_substancia_produto', 'medicamentos', ['substancia', 'produto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medicamentos_substancia_produto', table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_substancia'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_produto'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_codigo_ggrem'), table_name='medicamentos')
    op.drop_table('medicamentos')
    # ### end Alembic commands ###
